attempt to fixed issues with nginx not loading css properly

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,15 +43,15 @@ jobs:
         # Sync static
         rsync -avz --exclude 'node_modules' -e "ssh -i key.pem -o StrictHostKeyChecking=no" . $VM_USERNAME@$VM_IP:/var/www/website-portfolio/
 
-        # For deplying nginx config
-        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" deploy/nginx.conf $VM_USERNAME@$VM_IP:/tmp/nginx.conf
+        # Deploy the Nginx configuration file
+        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" nginx.conf $VM_USERNAME@$VM_IP:/etc/nginx/sites-available/website-portfolio
 
-        # Updating nginx configuration
-        ssh -i key.pem -o StrictHostKeyChecking=no $VM_USERNAME@$VM_IP << EOF
-          sudo mv /tmp/nginx.conf /etc/nginx/sites-available/default
-          sudo nginx -t  # Test the configuration
-          sudo systemctl reload nginx
+        # Enable the configuration and restart Nginx
+        ssh -i key.pem -o StrictHostKeyChecking=no $VM_USERNAME@$VM_IP << 'EOF'
+          sudo ln -sf /etc/nginx/sites-available/website-portfolio /etc/nginx/sites-enabled/
+          sudo nginx -t && sudo systemctl reload nginx
         EOF
+
 
     - name: Configure and Start application
       env:
@@ -91,12 +91,16 @@ jobs:
           fi
 
           # Start the Next.js application with PM2
-          if [ -f /var/www/website-portfolio/standalone/server.js ]; then
-              pm2 start /var/www/website-portfolio/standalone/server.js --name "website-portfolio"
-          else
-              echo "Error: Script not found: /var/www/website-portfolio/standalone/server.js"
-              exit 1
-          fi
+          pm2 start npm --name "website-portfolio" -- start || true
+
+          
+          # Start the Next.js application with PM2
+          #     pm2 start /var/www/website-portfolio/standalone/server.js --name "website-portfolio"
+          # else
+          #     echo "Error: Script not found: /var/www/website-portfolio/standalone/server.js"
+          #     exit 1
+          # fiif [ -f /var/www/website-portfolio/standalone/server.js ]; then
+          
 
           # Save the PM2 process list
           pm2 save
